### ISSUE TITLE
[question] subtle difference between [buildenv] and [env]?

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#13824]
### What is your question?

Hi,

see this post for failing cross-build of libsystemd: https://github.com/conan-io/conan-center-index/issues/17270#issuecomment-1534901887

Is there any difference in the implementation of `[buildenv]` compared to `[env]` which explains this behaviour?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

There are many differences in how ``env`` and ``buildenv`` behave, like ``env`` is setting things in memory env-vars in the Python process and ``buildenv`` works via generated files that are pre-pended to the build command in ``self.run()`` execution.

Still, I don't see any reason why it would work by defining other different env-vars. I will try to have a look, but it would be much easier if we had some smaller repro case than using libsystemd (btw, does it happen only with this recipe? Or you can reproduce also with some other recipes?)

**Comment by memsharded** [comment]
I am trying to reproduce, but I can't get the dependencies built:
```
      |           ^~~
In file included from /home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/libmount/src/context.c:42:
/home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/include/namespace.h:43:19: error: static declaration of ‘unshare’ follows non-static declaration
   43 | static inline int unshare(int flags)
      |                   ^~~~~~~
In file included from /usr/aarch64-linux-gnu/include/sched.h:43,
                 from /home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/include/namespace.h:11,
                 from /home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/libmount/src/context.c:42:
/usr/aarch64-linux-gnu/include/bits/sched.h:86:12: note: previous declaration of ‘unshare’ was here
   86 | extern int unshare (int __flags) __THROW;
      |            ^~~~~~~
In file included from /home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/libmount/src/context.c:42:
/home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/include/namespace.h:50:19: error: static declaration of ‘setns’ follows non-static declaration
   50 | static inline int setns(int fd, int nstype)
      |                   ^~~~~
In file included from /usr/aarch64-linux-gnu/include/sched.h:43,
                 from /home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/include/namespace.h:11,
                 from /home/conan/.conan2/p/t/libmo58d374af7c94e/b/src/libmount/src/context.c:42:
/usr/aarch64-linux-gnu/include/bits/sched.h:95:12: note: previous declaration of ‘setns’ was here
   95 | extern int setns (int __fd, int __nstype) __THROW;
      |            ^~~~~
  CC       libmount/src/la-context_mount.lo
make[2]: *** [Makefile:10154: libmount/src/la-context.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```
libmount is failing to build in 2.0 with that profile. Any hint?

**Comment by tbsuht** [comment]
Yeah, sorry it is a bad example for debugging, but I don't have another yet. My suspicion is that this is also related somehow to meson and I'm not using meson anywhere.

For the libmount build problem you need libcrypt locally installed as mentioned here: https://github.com/conan-io/conan-center-index/issues/15101#issuecomment-1376869276

Probably you also need to locally build the ninja package as the one on conan center is not working currently: https://github.com/conan-io/conan-center-index/issues/17390

**Comment by tbsuht** [comment]
@memsharded I think my thought about meson might be right. Just searched for other projects using meson on conancenter and tried `glib` which is also failing with the same error message.

**Comment by memsharded** [comment]
Failed to install libcrypt in my docker (ubuntu).

Good hint!

Checking the MesonToolchain code:
```python
 self.c_ld = build_env.get("CC_LD") or build_env.get("LD")
        #: Defines the Meson ``cpp_ld`` variable. Defaulted to ``CXX_LD`` or ``LD`` build
        #: environment value
        self.cpp_ld = build_env.get("CXX_LD") or build_env.get("LD")
```

Not sure why your ``CCLD`` and ``CXXLD`` would work, because they are not applied here.

I would definitely recommended to try to reduce that to reproduce with a ``conan new meson_lib -d name=pkg -d version=0.1``, it seems the key is here, how Meson understand the env-vars.

**Comment by tbsuht** [comment]
Just for clarification, I'm using `CCLD` because of this issue in the meson bug tracker: https://github.com/mesonbuild/meson/issues/6442

**Comment by tbsuht** [comment]
> Failed to install libcrypt in my docker (ubuntu).

Hm, I'm using a debian based container: `FROM debian:bullseye`
The actual name is `libcrypt-dev:arm64` ... did you try that?

**Comment by memsharded** [comment]
The documentation https://mesonbuild.com/Reference-tables.html defines CC_LD and CXX_LD

**Comment by tbsuht** [comment]
> I would definitely recommended to try to reduce that to reproduce with a `conan new meson_lib -d name=pkg -d version=0.1`, it seems the key is here, how Meson understand the env-vars.

@memsharded Thanks! I can reproduce it with that.

The problem seems to be that you are not allowed to set `LD` to the cross-linker when cross compiling when using meson? That is annoying as other build systems have no problem with that.

**Comment by memsharded** [comment]
In theory it should, the code contains ``build_env.get("LD")``, so it should work.

**Comment by tbsuht** [comment]
Yeah, but it seems there is a mixup of the build and host machine linker. It seems the cross-linker is chosen for the build machine

If I set `LD` to the cross-linker
```
../meson.build:1:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not /usr/bin/aarch64-linux-gnu-ld.
```

If I use `CC_LD`:
```
C++ compiler for the host machine: /usr/bin/aarch64-linux-gnu-g++ (gcc 10.2.1 "aarch64-linux-gnu-g++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: /usr/bin/aarch64-linux-gnu-g++ ld.bfd 2.35.2
C++ compiler for the build machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the build machine: c++ ld.bfd 2.35.2
```

**Comment by tbsuht** [comment]
But using Conan 1.x this was working using `LD` and `[env]`.

**Comment by tbsuht** [comment]
> > I would definitely recommended to try to reduce that to reproduce with a `conan new meson_lib -d name=pkg -d version=0.1`, it seems the key is here, how Meson understand the env-vars.
> 
> @memsharded Thanks! I can reproduce it with that.
> 

@memsharded Have you also been able to reproduce it with that?

**Comment by tbsuht** [comment]
@memsharded any update on this problem?

**Comment by tbsuht** [comment]
@memsharded Sorry, I need to ping again, because the behavior is different and I don't have a simple workaround.

**Comment by tbsuht** [comment]
> Failed to install libcrypt in my docker (ubuntu).
> 
> Good hint!
> 
> Checking the MesonToolchain code:
> 
> ```python
>  self.c_ld = build_env.get("CC_LD") or build_env.get("LD")
>         #: Defines the Meson ``cpp_ld`` variable. Defaulted to ``CXX_LD`` or ``LD`` build
>         #: environment value
>         self.cpp_ld = build_env.get("CXX_LD") or build_env.get("LD")
> ```
> 
> Not sure why your `CCLD` and `CXXLD` would work, because they are not applied here.
> 
> I would definitely recommended to try to reduce that to reproduce with a `conan new meson_lib -d name=pkg -d version=0.1`, it seems the key is here, how Meson understand the env-vars.

Are `LD` and `CC_LD` only read from the `[buildenv]` and not `[env]` (tried to trace what is inside the `build_env` variable`)?
This would at least explain why it was working with this approach.

**Comment by tbsuht** [comment]
@memsharded According to [this comment ](https://github.com/mesonbuild/meson/issues/8647#issuecomment-818904324) about `c_ld/cpp_ld`, the current implementation looks wrong. E.g. `LD` will contain a full-path to the linker and `c_ld` only expects the paramter for `-fuse-ld` which will result in something like this:
```
../source/meson.build:3:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not /usr/bin/aarch64-linux-gnu-ld.
```

**Comment by tbsuht** [comment]
@memsharded *push*

We are running into more trouble with this, as 3rd-party projects which are build via meson _must not_ have LD defined in the cross-compile scenario ... but other projects especially using autotools will not build without LD defined.

I don't want to introduce separate profiles in our CI now ...

**Comment by memsharded** [comment]
Hi @tbsuht 

Sorry for the delays in answering, we are extremely busy, and it is very complicated to find the time to investigate things like this one that are very challenging to setup and reproduce (I wasn't able to reproduce so far).

So in order to have some chance to understand what is happening and possible ways, it would be great to have:
- To define a running environment, maybe starting with some docker image, like ``docker run -it -v conanio/gcc11`` and specify the exact commands that need to be run to install the necessary tools as cross-compilers, so we have the exact same environment.
- To define the exact profiles that are being used
- To run it on the ``conan new meson_lib`` template from latest Conan 2.0. Run it with ``conan create . -pr=myprofile`` (and it should fail)

If we are able to reproduce this and make it fail, then we would be in a much better position. Thanks!

In any case, it could be that fixing the LD thing in https://github.com/conan-io/conan/issues/14028 solves the issue, I don't know enough about meson to know, but lets try to check that, it seems that @Talkless has some other insights in that ticket.

**Comment by tbsuht** [comment]
Hi @memsharded

here is a setup, I'm using `conan 1.60.1`:

Dockerfile
```
FROM debian:bookworm

WORKDIR /root

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash

RUN apt-get update && apt-get install -q -y --no-install-recommends python3 python3-venv
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN apt-get update && apt-get install -q -y --no-install-recommends \
       apt-utils \
       apt-transport-https \
       g++ \
       g++-aarch64-linux-gnu \
       gcc \
       gcc-aarch64-linux-gnu \
       gcc-arm-linux-gnueabihf \
       make \
       python3 \
       python3-dev \
       python3-pip \
       sudo \
       pkg-config \
       meson \
       && pip install conan==1.60.1 \
       && rm -rf /var/lib/apt/lists/*

RUN echo "root:root" | chpasswd
RUN echo "ALL ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopassword
RUN echo "Defaults env_keep += \"http_proxy https_proxy no_proxy\"" >> /etc/sudoers.d/env_keep

CMD [ "/bin/bash" ]

```

Profile
```
{% set target_host = "/usr/bin/aarch64-linux-gnu" %}

[buildenv]
QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
LD='/usr/bin/aarch64-linux-gnu-ld'
CC={{ target_host + '-gcc' }}
CXX={{ target_host + '-g++' }}
STRIP={{ target_host + '-strip' }}
RANLIB={{ target_host + '-ranlib' }}
AR={{ target_host + '-ar' }}
AS={{ target_host + '-as' }}
OBJCOPY={{ target_host + '-objcopy' }}
CCLD={{ target_host + '-ld' }}
ARCH=arm64

[options]
*:shared=True

[conf]
tools.env.virtualenv:auto_use=True

[settings]
os=Linux
arch=armv8
compiler=gcc

compiler.version=10.2
compiler.libcxx=libstdc++11
compiler.cppstd=gnu17
```

Run 
```
conan new -m meson_lib pkg/1.0.0@
conan create . -pr:h /tmp/profile/linux_arm64_bookworm_WITH_LD -pr:b default
```

The error messages lightly changed, probably due to the newer version of meson as I just updated from debian bullseye to bookworm.

Log 
```
# conan create . -pr:h /tmp/profile/linux_arm64_bookworm_WITH_LD -pr:b default
Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=12
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
pkg/1.0.0 exports_sources: Copied 1 '.build' file: meson.build
pkg/1.0.0 exports_sources: Copied 1 '.cpp' file: pkg.cpp
pkg/1.0.0 exports_sources: Copied 1 '.h' file: pkg.h
pkg/1.0.0: A new conanfile.py version was exported
pkg/1.0.0: Folder: /root/.conan/data/pkg/1.0.0/_/_/export
pkg/1.0.0: Exported revision: 07dda6c15622f33b47ab36137d0cc2b2
Configuration (profile_host):
[settings]
arch=armv8
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=10.2
os=Linux
[options]
*:shared=True
[build_requires]
[env]
[conf]
tools.env.virtualenv:auto_use=True
[buildenv]
QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
CC=/usr/bin/aarch64-linux-gnu-gcc
CXX=/usr/bin/aarch64-linux-gnu-g++
STRIP=/usr/bin/aarch64-linux-gnu-strip
RANLIB=/usr/bin/aarch64-linux-gnu-ranlib
AR=/usr/bin/aarch64-linux-gnu-ar
AS=/usr/bin/aarch64-linux-gnu-as
OBJCOPY=/usr/bin/aarch64-linux-gnu-objcopy
CCLD=/usr/bin/aarch64-linux-gnu-ld
ARCH=arm64
LD='/usr/bin/aarch64-linux-gnu-ld'

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=12
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

pkg/1.0.0: Forced build from source
pkg/1.0.0 (test package): Installing package
Requirements
    pkg/1.0.0 from local cache - Cache
Packages
    pkg/1.0.0:62a64fc536074a130cdd4fa9c189bf2ba7539d45 - Build

Cross-build from 'Linux:x86_64' to 'Linux:armv8'
Installing (downloading, building) binaries...
pkg/1.0.0: Configuring sources in /root/.conan/data/pkg/1.0.0/_/_/source/.
pkg/1.0.0: Copying sources to build folder
pkg/1.0.0: Building your package in /root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45
pkg/1.0.0: Generator txt created conanbuildinfo.txt
pkg/1.0.0: Calling generate()
pkg/1.0.0: Aggregating env generators
pkg/1.0.0: Calling build()
pkg/1.0.0: Meson configure cmd: meson setup --cross-file "/root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/build/conan/conan_meson_cross.ini" "/root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/build" "/root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/." -Dprefix="/root/.conan/data/pkg/1.0.0/_/_/package/62a64fc536074a130cdd4fa9c189bf2ba7539d45"

ERROR: Malformed value in machine file variable 'c_ld'.
pkg/1.0.0:
pkg/1.0.0: ERROR: Package '62a64fc536074a130cdd4fa9c189bf2ba7539d45' build failed
pkg/1.0.0: WARN: Build folder /root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/build
ERROR: pkg/1.0.0: Error in build() method, line 32
        meson.configure()
        ConanException: Error 1 while executing meson setup --cross-file "/root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/build/conan/conan_meson_cross.ini" "/root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/build" "/root/.conan/data/pkg/1.0.0/_/_/build/62a64fc536074a130cdd4fa9c189bf2ba7539d45/." -Dprefix="/root/.conan/data/pkg/1.0.0/_/_/package/62a64fc536074a130cdd4fa9c189bf2ba7539d45"
```

**Comment by jwillikers** [comment]
@tbsuht You need to set `CC_LD` and `CXX_LD` in `[buildenv]` for Meson and you can _not_ set it the full path. Meson will automatically use the linker associated with the compiler. You can only override the argument used for this linker, i.e. by setting `CC_LD` to `gold` or `lld`.
