### ISSUE TITLE
conan config install no longer works with 1.11.0

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#4169]
With conan v1.11.0:

```
conan config install http://rambo.local:8090/jenkins/job/microblink/job/conan-toolchains/job/master/lastSuccessfulBuild/artifact/android.zip 
Trying to download  http://rambo.local:8090/jenkins/job/microblink/job/conan-toolchains/job/master/lastSuccessfulBuild/artifact/android.zip
ERROR: Error downloading file http://rambo.local:8090/jenkins/job/microblink/job/conan-toolchains/job/master/lastSuccessfulBuild/artifact/android.zip: ''tuple' object has no attribute 'get''
```

With conan v1.10.2 and earlier this works correctly. Our local CI server (that builds profile zips for company-wide use) is in local area network and does not use SSL (I guess #4158 could be related to breaking this behaviour). Are there any workarounds you could suggest?

**Comment by danimtb** [comment]
Seems the offending line is this one: https://github.com/conan-io/conan/pull/4062/files#diff-633cc9158b73bec9defbb8eb390ba040R573

I am fixing this ASAP. Thanks for reporting!

**Comment by lasote** [comment]
Conan 1.11.1 has been released.
