### ISSUE TITLE
[bug] Conan 2.27.0 breaks gdal build on Windows

### ISSUE THREAD

**Issue by timpatt** [conan-io/conan#19857]
### Describe the bug

I understand that the `gdal/3.4.3` conancenter recipe is not supported anymore, but this seems to be a Conan regression; it builds correctly on Windows with Conan 2.26.2, but breaks with Conan 2.27.0

I suspect the issue is caused by this change: #19779

Conan 2.26.2 (working) renders `conannmakedeps.bat` the `set "CL=%CL% ...` line as: `/D"SQLITE_API#"__declspec(dllimport)""`
Conan 2.27.0 (broken) renders the same line as `/D"SQLITE_API#\"__declspec(dllimport)\""`.

The resulting build errors are `<conan_home>\p\sqlit7a526c84c076b\p\include\sqlite3.h(185): error C2059: syntax error: 'string' (compiling source file hugefileresolver.cpp)` - one error for basically every line that contains a `SQLITE_API` macro.

**Comment by AbrilRBS** [comment]
Hi @timpatt thanks a lot for taking the time to report this, we appreciate it.

In fact, this seems like a regression from 2.26, where we changed how we escape quotes in nmake for definitions. I've proposed #19859 to revert those changes while keeping the numerical fix, but note that investigating the issue exposed a bug in the old escaping of defines too, but coming from the profile.

As these kinds of definitions are usually coming from recipes, we accepted that going back to the old behaviour (even if it's still buggy) is preferrable.

This fix will be released for next 2.27.1 early next week, thanks for your patience :)

**Comment by timpatt** [comment]
Hmmm.  Interesting! I'm pretty sure that I'm not running into any issues with CONAN 2.26.2 (I can confirm on Monday). How could that be if the issue was introduced in 2.26?

**Comment by czoido** [comment]
Closed by https://github.com/conan-io/conan/pull/19859 fixed for Conan 2.27.1 that will be release today
