### ISSUE TITLE
[bug] CompatiblePackage is gone in 1.21

### ISSUE THREAD

**Issue by db4** [conan-io/conan#6206]
### Environment Details (include every applicable attribute)
  * Conan version: 1.21.0

I'm trying to build a recipe using `CompatiblePackage` that worked in 1.20.x. After the upgrade to 1.21.0 it fails:
```
    from conans import ConanFile, CompatiblePackage, CMake, tools, __version__ as conan_version
ImportError: cannot import name 'CompatiblePackage' from 'conans' (c:\python37\lib\site-packages\conans\__init__.py)
```
And I see no traces of `CompatiblePackage` in conan's sources. Is it removed completely?

**Comment by memsharded** [comment]
Hi @db4 

Yes, the interface has changed, but the feature is still there. Please check the new syntax in: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages

The thing is that we couldn't leverage all the features in the ``self.info`` field, so we decided to change it and use a ``self.info.clone()`` instead of maintaining a separate class. As it was introduced in last release as experimental, we preferred to fix the interface asap, sorry for the inconvenience, but will be better in the long term.

**Comment by db4** [comment]
@memsharded 
Thanks a lot for a really quick response. I knew it's an experimental feature, but I thought [Changelog](https://docs.conan.io/en/latest/changelog.html) could contain something like `CompatiblePackage: replaced with...`. I had searched the changelog for `CompatiblePackage`, found nothing and then created this issue. Now it's clear, thank you once again.

**Comment by memsharded** [comment]
Yes, that is true, the PR was https://github.com/conan-io/conan/pull/6052, but it only included the description of Intel compiler, not the necessary changes that were done to support it, including this one. Sorry for the confusion!
