### ISSUE TITLE
[question] How to work in Debug mode with CMakeDeps and CMakeToolchain

### ISSUE THREAD

**Issue by Kidsunbo** [conan-io/conan#11175]
Hi, I have a header-only library with `cmake` generator and it works fine. I've migrated it to `CMakeDeps` and `CMakeToolchain`. When consuming this library, it works in Conan 1.47. But I found that the output binary is compiled in Release mode. I think it's due to the `CMAKE_BUILD_TYPE` is set to `Release` in the `conan_toolchain.cmake`. 

So first question: Why is the `CMAKE_BUILD_TYPE` still set to `Release` even I `conan install` with `-pr:b=debug_profile`? The `debug_profile` looks like this:
```[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Debug
[options]
[build_requires]
[env]

```

After upgrading Conan to 1.48, setting `CMAKE_BUILD_TYPE` statement is gone in `conan_toolchain.cmake`. Now it can not work in Debug mode but work in Release mode. It failed to find the header even I pass `-DCMAKE_BUILD_TYPE=Debug` to cmake according to https://github.com/conan-io/conan/issues/11167 . How to solve this?

Here is the `conanfile.txt`:
```
[requires]
boost/1.78.0

[generators]
CMakeDeps
CMakeToolchain
```

and my `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.0.0)
project(kies VERSION 0.1.0)

set(CMAKE_CXX_STANDARD 20)

find_package(Boost REQUIRED)

add_executable(kies main.cpp)
target_link_libraries(kies PUBLIC boost::boost)
```

The `main.cpp` looks like this:
```
#include <iostream>
#include <boost/asio.hpp>


int main(int, char**) {
    std::cout << "Hello, world!\n";
}

```

When I compile, it shows 
```
[main] Building folder: temp 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /root/temp/build --config Debug --target all -j 12 --
[build] [ 50%] Building CXX object CMakeFiles/kies.dir/main.cpp.o
[build] /root/temp/main.cpp:2:10: fatal error: boost/asio.hpp: No such file or directory
[build]     2 | #include <boost/asio.hpp>
[build]       |          ^~~~~~~~~~~~~~~~
[build] compilation terminated.
[build] gmake[2]: *** [CMakeFiles/kies.dir/build.make:76: CMakeFiles/kies.dir/main.cpp.o] Error 1
[build] gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/kies.dir/all] Error 2
[build] gmake: *** [Makefile:91: all] Error 2
[build] Build finished with exit code 2
```
## Environment Details
Operating System+version: Ubuntu 22.04
Compiler+version: GCC 11.2
Conan version: 1.48.0
Python version: 3.10
CMake version: 3.22.1

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Kidsunbo 

I think there is a mistake there in ``-pr:b=debug_profile``

You are applying the build profile only to the "build" context. You need to specify it to the ``-pr:h=debug_profile`` to the "host" context, if you want your libraries and executables to be in "debug", otherwise you are telling only your "tool_requires", like ``cmake``, to use debug binaries, which is likely something that you don't want.

So this is the reason the dependency is not found, you are installing for ``Release``, and trying to consume for ``Debug``.

**Comment by Kidsunbo** [comment]
> Hi @Kidsunbo
> 
> I think there is a mistake there in `-pr:b=debug_profile`
> 
> You are applying the build profile only to the "build" context. You need to specify it to the `-pr:h=debug_profile` to the "host" context, if you want your libraries and executables to be in "debug", otherwise you are telling only your "tool_requires", like `cmake`, to use debug binaries, which is likely something that you don't want.
> 
> So this is the reason the dependency is not found, you are installing for `Release`, and trying to consume for `Debug`.

In `cmake` generator, is there any limitation like this? I remember I was able to link Release library to my debug binary with `cmake` generator.

I use `conan install .. -pr:b=debug_profile -pr:h=debug_profile` and it works this time. Thank you. 

There seems no warning for missing `-pr:h` in cli. Do I need to use `conan install` with `-pr:b` and `-pr:h` everytime if I switch between `Debug` and `Release`.And if I am right, is there any shortcut for these two options? like `-pr=profile`.

**Comment by memsharded** [comment]
> In cmake generator, is there any limitation like this? I remember I was able to link Release library to my debug binary with cmake generator.

``cmake`` generator is always single-config, which is limited for many users like Windows and Xcode that are multi-config, this is one of the reasons it has been deprecated. Also the fact that it is intrusive.

> There seems no warning for missing -pr:h in cli. Do I need to use conan install with -pr:b and -pr:h everytime if I switch between Debug and Release.And if I am right, is there any shortcut for these two options? like -pr=profile.

It is necessary in 1.X, in Conan 2.0 the build profile will be used by default (pointing to the ``default`` profile).

You might try adding to your ``global.conf`` the following too:
```
"core:default_profile": "Defines the default host profile ('default' by default)",
"core:default_build_profile": "Defines the default build profile (None by default)",
```

At least the ``default_build_profile``, to avoid it

**Comment by Kidsunbo** [comment]
> 

OK, thanks for your reply. It's pretty clear, and I have no question now. thank you very much.
