### ISSUE TITLE
[bug] Error in build_requires.add since Conan 1.23.0

### ISSUE THREAD

**Issue by v-strob** [conan-io/conan#6667]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.14.4
  * Compiler+version: Xcode 11.3.1 (AppleClang)
  * Conan version: 1.23.0
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)
1. git clone https://gitlab.com/ssrobins/conan-zlib
2. cd conan-zlib
3. ./build_mac.sh

I get this error:
```
ERROR: zlib/1.2.11: Error in build_requirements() method, line 25
self.build_requires.add("cmake_utils/0.3.1#7b308615a235fdf046db096dd35325c0375c2f88")
	TypeError: add() missing 1 required positional argument: 'context'
```

Worked fine in Conan 1.22.3. Note that I have CONAN_REVISIONS_ENABLED set to 1

CI config:
https://gitlab.com/ssrobins/conan-zlib/-/blob/stable/.gitlab-ci.yml

Full output from CI:
https://gitlab.com/ssrobins/conan-zlib/-/jobs/468727314

**Comment by jgsogo** [comment]
Hi @v-strob , the documented way to add requires and build_requires is _without the `.add`_. Have a look here: https://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=build_requires#build-requirements

```
class MyPkg(ConanFile):

    def build_requirements(self):
        if self.settings.os == "Windows":
            self.build_requires("ToolWin/0.1@user/stable")
```

Yes, there are changes in the internals related to the new cross-building model, but the documented behavior keeps working the same.

Thanks!

**Comment by v-strob** [comment]
Thanks for the tip. I swear the docs used to list the add method...

I logged this because of this statement in the docs:
Conan 1.23 shouldn’t break any existing 1.0 recipe or command line invocation. If it does, please submit a report on GitHub. Read more about the Conan stability commitment.

It would be helpful if the changelog called out API breaks, when the above statement does not apply.

**Comment by jgsogo** [comment]
Yes, that commitment is only possible for documented elements. In Python there is no such a concept of private member/variables, so it is nos possible to block the user from accessing anything.

Thanks for the suggestion

**Comment by memsharded** [comment]
Yes, the docs also say this, to clarify what is the stable part:

> Only documented features are considered part of the public interface of Conan. Private implementation details, and everything not included in the documentation is subject to change.

**Comment by memsharded** [comment]
BTW, docs are versioned too, we can see back in time:
- https://docs.conan.io/en/1.3/devtools/build_requires.html
- https://docs.conan.io/en/1.3/reference/conanfile/methods.html#build-requirements

**Comment by v-strob** [comment]
I guess I must've pasted code from somewhere else if it's never been documented that way. No big deal. Thanks for the explanation.
