### ISSUE TITLE
[bug] conan doesn't work on python 3.5 anymore

### ISSUE THREAD

**Issue by db4** [conan-io/conan#9019]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04 LTS
  * Conan version: 1.36.0
  * Python version: 3.5.1 

### Steps to reproduce

```
sudo docker run --rm -it ubuntu:xenial
...
root@1b0f413b4aac:/# apt update
root@1b0f413b4aac:/# apt -y install python3-pip
root@1b0f413b4aac:/# pip3 install conan
root@1b0f413b4aac:/# conan --version
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 7, in <module>
    from conans.conan import run
  File "/usr/local/lib/python3.5/dist-packages/conans/conan.py", line 7, in <module>
    from conans.client.command import main
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 11, in <module>
    from conans.client.cache.cache import ClientCache
  File "/usr/local/lib/python3.5/dist-packages/conans/client/cache/cache.py", line 6, in <module>
    from jinja2 import Environment, select_autoescape, FileSystemLoader, ChoiceLoader
  File "/usr/local/lib/python3.5/dist-packages/jinja2/__init__.py", line 6, in <module>
    from markupsafe import escape
ImportError: cannot import name 'escape'
```

**Comment by db4** [comment]
BTW, a couple of weeks ago Conan 1.36.0 worked on that `ubuntu:xenial` docker image. Since then the image itself has been updated as well as some Conan dependencies. But I can't say what exactly triggers the issue.

**Comment by memsharded** [comment]
Yes, Python 3.5 is EOL already, in this case it seems that jinja2 dependency on MarkupSafe broke support for Python 3.5.

I have had success downgrading it to:
```
pip3 install MarkupSafe==1.1.1 --upgrade
```

And latest jinja2:
```
from setuptools import setup

# Metadata goes in setup.cfg. These are here for GitHub's dependency graph.
setup(
    name="Jinja2",
    install_requires=["MarkupSafe>=2.0"],
    extras_require={"i18n": ["Babel>=2.7"]},
)
```

**Comment by db4** [comment]
> Yes, Python 3.5 is EOL already

So this won't be fixed in Conan? It still declares python 3.5 support (https://docs.conan.io/en/latest/installation.html) and I thought it should work.

**Comment by memsharded** [comment]
Conan itself seems to keep working, as long as the dependencies keep working, and in this case it seems something broke in the python ecosystem for Python 3.5, steps to reproduce:

```
root@1b0f413b4aac:/# apt update
root@1b0f413b4aac:/# apt -y install python3-pip
root@cf0dc5fa14b8:/# pip3 install "Jinja2>0,<3.0"
Collecting Jinja2<3.0,>0
  Downloading https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl (125kB)
    100% |################################| 133kB 5.3MB/s
Collecting MarkupSafe>=0.23 (from Jinja2<3.0,>0)
  Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz
  Requested MarkupSafe>=0.23 from https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz#sha256=594c67807fb16238b30c44bdf74f36c02cdf22d1c8cda91ef8a0ed8dabf5620a (from Jinja2<3.0,>0), but installing version None
Building wheels for collected packages: MarkupSafe
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /root/.cache/pip/wheels/21/8d/8d/03713c46963ee240d5105dd963d75b655461e13c95332962c4
Successfully built MarkupSafe
Installing collected packages: MarkupSafe, Jinja2
Successfully installed Jinja2-2.11.3 MarkupSafe-0.0.0
You are using pip version 8.1.1, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

root@cf0dc5fa14b8:/# python3
Python 3.5.2 (default, Jan 26 2021, 13:30:48)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jinja2 import Environment, select_autoescape, FileSystemLoader, ChoiceLoader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/__init__.py", line 6, in <module>
    from markupsafe import escape
ImportError: cannot import name 'escape'
>>>
```

I am checking what could be done, seems a problem of old pip (8.1) that for some reason mess with the transitive dependencies between Jinja2 and MarkupSafe, and installs a somehow 0.0.0 broken Markupsafe.

**Comment by memsharded** [comment]
Installation with ``pip3 install conan MarkupSafe==1.1.1`` seems to be work so far, I think at the moment this could be the best solution. The thing is that if we try to define the dependency to MarkupSafe directly in the ``requirements.txt``, there is a chance that we could be breaking other users (at the moment it does not depend directly on it), even if we condition it to Python3.5, as it is possible that users with Python3.5 that managed to update pip itself, will not have this problem?

**Comment by memsharded** [comment]
Yes, it seems that the above
```
pip3 install conan MarkupSafe==1.1.1
```

could be the best that could be done. 
Because older versions of pip (like the one used) is ignoring environment markers, so 

```
pip3 install conan MarkupSafe==1.1.1; python_version=='3.5'
```

are ignored, which could be causing errors to other users in different python versions.

**Comment by db4** [comment]
> `pip3 install conan MarkupSafe==1.1.1`

@memsharded, it looks like an acceptable workaround, so I'm closing the issue. Thanks a lot!

**Comment by SallySoul** [comment]
As an update, I also had to fix the jinja2 version to keep conan working on xenial
```
pip3 install conan MarkupSafe==1.1.1 jinja2==2.11.2
```
