### ISSUE TITLE
[bug] Library included using conan 2 is not detected during building

### ISSUE THREAD

**Issue by brookite** [conan-io/conan#15406]
### Environment details

* Operating System+version: WSL (Debian 12)
* Compiler+version: gcc 12.2.0
* Conan version: 2.0.16
* Python version: 3.11.2

### Steps to reproduce

I want to include the treesitter library to my project, however the tree_sitter/api.h file was not found when compiling the main executable main.cpp

Steps:
1. `conan install . --output-folder=build --build=missing`
2. `cd build`
3. `cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Debug`
4. `cmake --build . --config Debug`

main.cpp
```c++
#include <stdio.h>
#include <string.h>

extern "C"
{
#include <tree_sitter/api.h>
}

int main() {
  TSParser *parser = ts_parser_new();
  ts_parser_delete(parser);
  return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.20)

project(MeaningTree)

find_package(tree-sitter REQUIRED CONFIG)
find_package(gtest REQUIRED)

add_subdirectory(lib)
add_subdirectory(tests)

add_executable(${PROJECT_NAME} parsers/tree-sitter-java/src/parser.c main.cpp)
target_link_libraries(${PROJECT_NAME} tree-sitter::tree-sitter)
target_link_libraries(${PROJECT_NAME} lib)
target_link_libraries(${PROJECT_NAME} gtest)
```

tree:
```
├── CMakeLists.txt
├── CMakeUserPresets.json
├── conanfile.txt
├── parsers/tree-sitter-java/src/parser.c
├── lib
│   ├── CMakeLists.txt
│   ├── functions.cpp
│   ├── functions.hpp
│   └── structures.hpp
├── main.cpp
├── README.md
└── tests
    ├── CMakeLists.txt
    └── test.cpp
```

### Logs

```
$ conan install . --output-folder=build --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.txt: /mnt/d/Projects/CompPrehensionProject/meaning_tree/conanfile.txt
Requirements
    gtest/1.14.0#4372c5aed2b4018ed9f9da3e218d18b3 - Cache
    tree-sitter/0.20.8#1d054460c5b08029a43079d23b090e2d - Cache

======== Computing necessary packages ========
Requirements
    gtest/1.14.0#4372c5aed2b4018ed9f9da3e218d18b3:6abc5cf15a93a0fe69ba9f89fd240c425083b2a7#9b16a10787e061282b728bc57ba60c41 - Cache
    tree-sitter/0.20.8#1d054460c5b08029a43079d23b090e2d:5bc851010eb7b707e5cb2e24cb8ccf0f27989fa9#c69912065f8c94a12da1d137227808fe - Cache

======== Installing packages ========
gtest/1.14.0: Already installed! (1 of 2)
tree-sitter/0.20.8: Already installed! (2 of 2)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: gtest/1.14.0

======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /mnt/d/Projects/CompPrehensionProject/meaning_tree/build
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(GTest)
    find_package(tree-sitter)
    target_link_libraries(... gtest::gtest tree-sitter::tree-sitter)
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: CMakeToolchain generated: conan_toolchain.cmake
conanfile.txt: Preset 'conan-release' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-release' if using CMake>=3.23
conanfile.txt: If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/mnt/d/Projects/CompPrehensionProject/meaning_tree/build/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.txt: CMakeToolchain generated: CMakePresets.json
conanfile.txt: CMakeToolchain generated: ../CMakeUserPresets.json
conanfile.txt: Generating aggregated env files
conanfile.txt: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
```

```
$ cd build
$ cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Debug
-- Using Conan toolchain: /mnt/d/Projects/CompPrehensionProject/meaning_tree/build/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 17 with extensions ON
-- Conan: Target declared 'tree-sitter::tree-sitter'
-- Conan: Component target declared 'GTest::gtest'
-- Conan: Component target declared 'GTest::gtest_main'
-- Conan: Component target declared 'GTest::gmock'
-- Conan: Component target declared 'GTest::gmock_main'
-- Conan: Target declared 'gtest::gtest'
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/Projects/CompPrehensionProject/meaning_tree/build
$ cmake --build . --config Debug
[ 14%] Building CXX object CMakeFiles/MeaningTree.dir/main.cpp.o
/mnt/d/Projects/CompPrehensionProject/meaning_tree/main.cpp:6:10: fatal error: tree_sitter/api.h: No such file or directory
    6 | #include <tree_sitter/api.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/MeaningTree.dir/build.make:90: CMakeFiles/MeaningTree.dir/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/MeaningTree.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

conan_toolchain.cmake
```

# Conan automatically generated toolchain file
# DO NOT EDIT MANUALLY, it will be overwritten

# Avoid including toolchain file several times (bad if appending to variables like
#   CMAKE_CXX_FLAGS. See https://github.com/android/ndk/issues/323
include_guard()

message(STATUS "Using Conan toolchain: ${CMAKE_CURRENT_LIST_FILE}")

if(${CMAKE_VERSION} VERSION_LESS "3.15")
    message(FATAL_ERROR "The 'CMakeToolchain' generator only works with CMake >= 3.15")
endif()




########## generic_system block #############
# Definition of system, platform and toolset
#############################################







string(APPEND CONAN_CXX_FLAGS " -m64")
string(APPEND CONAN_C_FLAGS " -m64")
string(APPEND CONAN_SHARED_LINKER_FLAGS " -m64")
string(APPEND CONAN_EXE_LINKER_FLAGS " -m64")



message(STATUS "Conan toolchain: C++ Standard 17 with extensions ON")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Extra c, cxx, linkflags and defines


if(DEFINED CONAN_CXX_FLAGS)
  string(APPEND CMAKE_CXX_FLAGS_INIT " ${CONAN_CXX_FLAGS}")
endif()
if(DEFINED CONAN_C_FLAGS)
  string(APPEND CMAKE_C_FLAGS_INIT " ${CONAN_C_FLAGS}")
endif()
if(DEFINED CONAN_SHARED_LINKER_FLAGS)
  string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT " ${CONAN_SHARED_LINKER_FLAGS}")
endif()
if(DEFINED CONAN_EXE_LINKER_FLAGS)
  string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${CONAN_EXE_LINKER_FLAGS}")
endif()

get_property( _CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE )
if(_CMAKE_IN_TRY_COMPILE)
    message(STATUS "Running toolchain IN_TRY_COMPILE")
    return()
endif()

set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)

# Definition of CMAKE_MODULE_PATH
# the generators folder (where conan generates files, like this toolchain)
list(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

# Definition of CMAKE_PREFIX_PATH, CMAKE_XXXXX_PATH
# The Conan local "generators" folder, where this toolchain is saved.
list(PREPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR} )
list(PREPEND CMAKE_LIBRARY_PATH "/home/brookit/.conan2/p/b/gtestc23afa693a338/p/lib" "/home/brookit/.conan2/p/b/tree-72a5d21ec93de/p/lib")
list(PREPEND CMAKE_INCLUDE_PATH "/home/brookit/.conan2/p/b/gtestc23afa693a338/p/include" "/home/brookit/.conan2/p/b/tree-72a5d21ec93de/p/include")



if (DEFINED ENV{PKG_CONFIG_PATH})
set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}:$ENV{PKG_CONFIG_PATH}")
else()
set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}:")
endif()




# Variables
# Variables  per configuration


# Preprocessor definitions
# Preprocessor definitions per configuration


if(CMAKE_POLICY_DEFAULT_CMP0091)  # Avoid unused and not-initialized warnings
endif()
```

**Comment by memsharded** [comment]
Hi @brookite 

I think this is not a Conan bug. It seems you are missing the specification of the build type of dependencies. The dependencies build type should be also ``Debug``, so you should specify it in:
```
conan install . --output-folder=build --build=missing -s build_type=Debug
```
Because otherwise, the default one is ``Release`` (you should be able to see it in the output of the ``conan install`` command).
Please try that and let use know.

**Comment by brookite** [comment]
Yes, it really works! Thank you very much!

**Comment by memsharded** [comment]
Great to know! 🙂

**Comment by memsharded** [comment]
I think we can close the issue by now, it seems the problem is solved. We have some ideas of potential improvements to help detecting this issue, but it is a bit challenging, so it might take some time.

Do not hesitate to open new tickets for any further question or issue you might have, thanks!

**Comment by thanhtungpfiev** [comment]
> Hi @brookite
> 
> I think this is not a Conan bug. It seems you are missing the specification of the build type of dependencies. The dependencies build type should be also `Debug`, so you should specify it in:
> 
> ```
> conan install . --output-folder=build --build=missing -s build_type=Debug
> ```
> 
> Because otherwise, the default one is `Release` (you should be able to see it in the output of the `conan install` command). Please try that and let use know.

You saved my life. Thank you so much
