### ISSUE TITLE
facing linking error when I upgraded conan version from 1.18.5 to 1.20.4

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#6145]
```
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "void __cdecl `eh vector destructor iterator'(void *,unsigned __int64,unsigned __int64,void (__cdecl*)(void *))" (??_M@YAXPEAX_K1P6AX0@Z@Z) referenced in function "public: virtual void * __cdecl Teamcenter::Soa::Internal::Gateway::GatewayResponse::`vector deleting destructor'(unsigned int)" (??_EGatewayResponse@Gateway@Internal@Soa@Teamcenter@@UEAAPEAXI@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl `eh vector destructor iterator'(void *,unsigned __int64,unsigned __int64,void (__cdecl*)(void *))" (??_M@YAXPEAX_K1P6AX0@Z@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl `eh vector destructor iterator'(void *,unsigned __int64,unsigned __int64,void (__cdecl*)(void *))" (??_M@YAXPEAX_K1P6AX0@Z@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2001: unresolved external symbol _purecall
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol _purecall
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol _purecall
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z) referenced in function "public: __cdecl MBS9::Services::Reports::_2016_10::ReportsServiceIiopSkeleton::ReportsServiceIiopSkeleton(void)" (??0ReportsServiceIiopSkeleton@_2016_10@Reports@Services@MBS9@@QEAA@XZ)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "void * __cdecl operator new(unsigned __int64)" (??2@YAPEAX_K@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete(void *)" (??3@YAXPEAX@Z) referenced in function "void __cdecl std::_Deallocate(void *,unsigned __int64,unsigned __int64)" (?_Deallocate@std@@YAXPEAX_K1@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *)" (??3@YAXPEAX@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *)" (??3@YAXPEAX@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete(void *,unsigned __int64)" (??3@YAXPEAX_K@Z) referenced in function "public: virtual __cdecl MBS9::Services::Reports::_2016_10::ReportsServiceIiopSkeleton::~ReportsServiceIiopSkeleton(void)" (??1ReportsServiceIiopSkeleton@_2016_10@Reports@Services@MBS9@@UEAA@XZ)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned __int64)" (??3@YAXPEAX_K@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned __int64)" (??3@YAXPEAX_K@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete[](void *,unsigned __int64)" (??_V@YAXPEAX_K@Z) referenced in function "public: virtual void * __cdecl Teamcenter::Soa::Internal::Gateway::GatewayResponse::`vector deleting destructor'(unsigned int)" (??_EGatewayResponse@Gateway@Internal@Soa@Teamcenter@@UEAAPEAXI@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *,unsigned __int64)" (??_V@YAXPEAX_K@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *,unsigned __int64)" (??_V@YAXPEAX_K@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol __imp__invalid_parameter_noinfo_noreturn referenced in function "void * __cdecl std::_Allocate(unsigned __int64,unsigned __int64,bool)" (?_Allocate@std@@YAPEAX_K0_N@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter_noinfo_noreturn
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter_noinfo_noreturn
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol memcmp referenced in function "public: static int __cdecl std::char_traits<char>::compare(char const * const,char const * const,unsigned __int64)" (?compare@?$char_traits@D@std@@SAHQEBD0_K@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol memcpy referenced in function "public: void __cdecl std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::_Assign_rv_contents_with_alloc_always_equal(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,struct std::integral_constant<bool,1>)" (?_Assign_rv_contents_with_alloc_always_equal@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAAX$$QEAV12@U?$integral_constant@_N$00@2@@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol memcpy
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol memcpy
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol __imp_memmove referenced in function "public: static char * __cdecl std::char_traits<char>::move(char * const,char const * const,unsigned __int64)" (?move@?$char_traits@D@std@@SAPEADQEADQEBD_K@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol __imp_memmove
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol __imp_memmove
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol strlen referenced in function "public: static unsigned __int64 __cdecl std::char_traits<char>::length(char const * const)" (?length@?$char_traits@D@std@@SA_KQEBD@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol strlen
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol strlen
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xbad_alloc(void)" (__imp_?_Xbad_alloc@std@@YAXXZ) referenced in function "void * __cdecl std::_Allocate(unsigned __int64,unsigned __int64,bool)" (?_Allocate@std@@YAPEAX_K0_N@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xbad_alloc(void)" (__imp_?_Xbad_alloc@std@@YAXXZ)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xbad_alloc(void)" (__imp_?_Xbad_alloc@std@@YAXXZ)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xlength_error(char const *)" (__imp_?_Xlength_error@std@@YAXPEBD@Z) referenced in function "protected: class std::_Tree_iterator<class std::_Tree_val<struct std::_Tree_simple_types<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)> > > > __cdecl std::_Tree<class std::_Tmap_traits<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &),struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)> >,0> >::_Insert_at<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)> &,struct std::_Tree_node<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)>,void *> *>(bool,struct std::_Tree_node<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)>,void *> *,struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)> &,struct std::_Tree_node<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,void (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)>,void *> *)" (??$_Insert_at@AEAU?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@PEAU?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@PEAX@2@@?$_Tree@V?$_Tmap_traits@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@ZU?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@@2@$0A@@std@@@std@@IEAA?AV?$_Tree_iterator@V?$_Tree_val@U?$_Tree_simple_types@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@@std@@@std@@@1@_NPEAU?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@PEAX@1@AEAU?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@1@1@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xlength_error(char const *)" (__imp_?_Xlength_error@std@@YAXPEBD@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xlength_error(char const *)" (__imp_?_Xlength_error@std@@YAXPEBD@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xout_of_range(char const *)" (__imp_?_Xout_of_range@std@@YAXPEBD@Z) referenced in function "public: static void __cdecl std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::_Xran(void)" (?_Xran@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@SAXXZ)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xout_of_range(char const *)" (__imp_?_Xout_of_range@std@@YAXPEBD@Z)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xout_of_range(char const *)" (__imp_?_Xout_of_range@std@@YAXPEBD@Z)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol _CxxThrowException referenced in function __catch$??$?0U?$_Wrap_alloc@V?$allocator@U?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@PEAX@std@@@std@@@std@@@?$_Tree@V?$_Tmap_traits@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@ZU?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@@2@$0A@@std@@@std@@QEAA@AEBV01@$$QEAU?$_Wrap_alloc@V?$allocator@U?$_Tree_node@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AXAEBV12@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z@std@@PEAX@std@@@std@@@1@@Z$0
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol _CxxThrowException
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol _RTC_CheckStackVars referenced in function "private: static void __cdecl MBS9::Services::Reports::_2016_10::ReportsServiceIiopSkeleton::getReportGraphData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class Teamcenter::Soa::Internal::Gateway::GatewayResponse &)" (?getReportGraphData@ReportsServiceIiopSkeleton@_2016_10@Reports@Services@MBS9@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVGatewayResponse@Gateway@Internal@Soa@Teamcenter@@@Z)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol _RTC_CheckStackVars
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol _RTC_CheckStackVars
ReportsService1610IiopSkeleton.cxx.obj : error LNK2001: unresolved external symbol _RTC_InitBase
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol _RTC_InitBase
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol _RTC_InitBase
ReportsService1610IiopSkeleton.cxx.obj : error LNK2001: unresolved external symbol _RTC_Shutdown
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol _RTC_Shutdown
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol _RTC_Shutdown
ReportsService1610IiopSkeleton.cxx.obj : error LNK2001: unresolved external symbol __CxxFrameHandler3
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol __CxxFrameHandler3
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol __CxxFrameHandler3
ReportsService1610IiopSkeleton.cxx.obj : error LNK2001: unresolved external symbol __GSHandlerCheck_EH
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol __GSHandlerCheck_EH
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol __GSHandlerCheck_EH
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol __RTDynamicCast referenced in function "public: virtual __cdecl MBS9::Services::Reports::_2016_10::ReportsServiceIiopSkeleton::~ReportsServiceIiopSkeleton(void)" (??1ReportsServiceIiopSkeleton@_2016_10@Reports@Services@MBS9@@UEAA@XZ)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol __security_check_cookie referenced in function "public: __cdecl MBS9::Services::Reports::_2016_10::ReportsServiceIiopSkeleton::ReportsServiceIiopSkeleton(void)" (??0ReportsServiceIiopSkeleton@_2016_10@Reports@Services@MBS9@@QEAA@XZ)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol __security_check_cookie
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol __security_check_cookie
ReportsService1610IiopSkeleton.cxx.obj : error LNK2001: unresolved external symbol "const type_info::`vftable'" (??_7type_info@@6B@)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol "const type_info::`vftable'" (??_7type_info@@6B@)
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol "const type_info::`vftable'" (??_7type_info@@6B@)
ReportsService1610IiopSkeleton.cxx.obj : error LNK2019: unresolved external symbol __security_cookie referenced in function "public: __cdecl MBS9::Services::Reports::_2016_10::ReportsServiceIiopSkeleton::ReportsServiceIiopSkeleton(void)" (??0ReportsServiceIiopSkeleton@_2016_10@Reports@Services@MBS9@@QEAA@XZ)
reportsservice1610.cxx.obj : error LNK2001: unresolved external symbol __security_cookie
reportsservice1610impl.cxx.obj : error LNK2001: unresolved external symbol __security_cookie
reportsservice1610.cxx.obj : error LNK2019: unresolved external symbol atexit referenced in function "void __cdecl `dynamic initializer for 'public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const MBS9::Soa::Reports::_2016_10::ReportsService::XSD_NAMESPACE''(void)" (??__E?XSD_NAMESPACE@ReportsService@_2016_10@Reports@Soa@MBS9@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B@@YAXXZ)
LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
bin\libMBS9SoaReports.dll : fatal error LNK1120: 26 unresolved externals
NMAKE : fatal error U1077: 'D:\apps\CMake\bin\cmake.exe' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: 'C:\apps\MVS15\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'C:\apps\MVS15\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe' : return code '0x2'
```

**Comment by memsharded** [comment]
Hi @Prasaddiwalkar 

Sorry to hear that something is not working.
Unfortunately the above information is not enough, with that we have no idea of what could be happening. We would need more information, ideally something, a minimal reproducible case that we can reproduce the issue with. You can put it in a repo, a zip file and attach it here, or specify what commands to execute to get that error. Thanks.

**Comment by Prasaddiwalkar** [comment]
I can not share my source code as per my organizations policy.

**Comment by memsharded** [comment]
Hi @Prasaddiwalkar 

Of course, not a problem if you cannot share your code. But the above linking trace is not enough to know what could be happening. It is typical to try to reduce the issue, removing the propietary bits, to the smallest possible thing (typically using just "hello world" simple source code) that can be used to reproduce the issue.  Or at least provide information about the compiler, the build system, the generators being used, the commands used that fire that issue, etc.

**Comment by Prasaddiwalkar** [comment]
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
*:tc_version=tc12.2.0
[build_requires]
[env]

generators :- Cmake

I tried with following generators.

- cmake .. -G "NMake Makefiles"

- cmake .. -G "Visual Studio 15 Win64"


- Command sequence.
   - conan install .. -o *:version=12.2.0
   - call %VC14HOME%\Auxiliary\Build\vcvars64.bat
   - cmake .. -G "NMake Makefiles"
   - cmake --build . --config Release

**Comment by memsharded** [comment]
Is the %VC14HOME% a typo? Shouldn't it be VC15HOME?
Also that step shouldn't be necessary, at least if using the ``"Visual Studio 15 Win64"`` cmake generator, it will manage to use the correct Visual Studio, no need to setup the environment.

**Comment by Prasaddiwalkar** [comment]
Yes it's a typo updated the comment.

Yes I agree if we mention "Visual Studio 15 Win64" calling vcvars64.bat is not needed.

I am trying to convey with both the options I am able to reproduce the issue.

**Comment by Prasaddiwalkar** [comment]
@memsharded any clue?

**Comment by memsharded** [comment]
Hi @Prasaddiwalkar 

No, sorry, no idea. I haven't been able to reproduce any linking error with the provided information. We haven't been reported a similar regression by any other user.
In order to keep investigating this issue we would need more information, some way to reproduce the failure, otherwise it is impossible to know. If you don't want to share it in public, feel free to send it privately to info@conan.io.

**Comment by memsharded** [comment]
Closing as stale and outdated
