### ISSUE TITLE
[bug] cannot import name 'BINARY_MISSING' from 'conan.api.model'

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#17653]
### Describe the bug

Environment: MacOS, Python 3.12, Conan 2.12.1

After updating from conan v2.11.0 to v2.12.1, when my custom commands get loaded, conan throws the following error:

```
[dodo@nm-nmiksa: sdk-document-verification-v2-ios (fix/documentation-build)]$ conan --version
ERROR: Error loading custom command 'cmd_merge_lists.py': cannot import name 'BINARY_MISSING' from 'conan.api.model' (/Users/dodo/.local/pipx/venvs/conan/lib/python3.12/site-packages/conan/api/model/__init__.py)
ERROR: Error loading custom command 'cmd_project.py': cannot import name 'BINARY_MISSING' from 'conan.api.model' (/Users/dodo/.local/pipx/venvs/conan/lib/python3.12/site-packages/conan/api/model/__init__.py)
Conan version 2.12.1
```

Downgrading back to v2.11.0 removes the problem. I've also tried with v2.12.0 and it also throws the error.

I've got 3 custom commands - two of them fail to load with the above error and one works normally even with v2.12

**Comment by DoDoENT** [comment]
For context, the `cmd_merge_lists.py` is very simple:

```python
# pylint: disable=missing-module-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=import-error
# pylint: disable=unused-argument

from argparse import ArgumentParser

from conan.api.conan_api import ConanAPI
from conan.cli.command import conan_command
from conan.api.model import MultiPackagesList, PackagesList

from utils import print_json_obj
from project_utils import merge_built_binaries


@conan_command(group='Microblink', formatters={"json": print_json_obj})
def merge_lists(conan_api: ConanAPI, parser: ArgumentParser, *args):
    """
    Merges multiple pkg list files into a single one.
    Works only for 'Local Cache'.
    """

    parser.add_argument(
        "-l", "--list",
        action="append",
        required=True,
        help="Pkg list files that should be merged. Argument can be given multiple times",
    )

    parsed_args = parser.parse_args(*args)

    merged = PackagesList()
    for lst in parsed_args.list:
        multi_pkg_list = MultiPackagesList.load(lst)
        merge_built_binaries(multi_pkg_list, merged)

    return {
        'Local Cache': merged.serialize(),
    }

```

`cmd_project.py` is too large to be attached here, but the problem appears also with `cmd_merge_lists.py`

**Comment by franramirez688** [comment]
Hi @DoDoENT 

I tried to reproduce it locally but I did not get it:

* Create virtualenv: Python 3.12 and Conan 2.11.0.
* Copy your custom command (without your specific modules):
```python
# pylint: disable=missing-module-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=import-error
# pylint: disable=unused-argument

from argparse import ArgumentParser

from conan.api.conan_api import ConanAPI
from conan.cli.command import conan_command
from conan.api.model import MultiPackagesList, PackagesList


@conan_command(group='Microblink')
def merge_lists(conan_api: ConanAPI, parser: ArgumentParser, *args):
    """
    Merges multiple pkg list files into a single one.
    Works only for 'Local Cache'.
    """

    parser.add_argument(
        "-l", "--list",
        action="append",
        required=True,
        help="Pkg list files that should be merged. Argument can be given multiple times",
    )

    parsed_args = parser.parse_args(*args)

    merged = PackagesList()
    for lst in parsed_args.list:
        multi_pkg_list = MultiPackagesList.load(lst)
    return {
        'Local Cache': merged.serialize(),
    }
```
* Run `conan --version` and `conan -h`:
```shell
$ conan -h
. . . 
Microblink commands
merge-lists Merges multiple pkg list files into a single one. Works only for 'Local Cache'.
```
* Now, update Conan version to 2.12.1 and run `conan -h` again:
```shell
$ conan -h
. . . 
Microblink commands
merge-lists Merges multiple pkg list files into a single one. Works only for 'Local Cache'.
```
Am I missing anything else?

**Comment by DoDoENT** [comment]
OK, if I remove invocation of function `merge_built_binaries`, it starts also working for me 🤔 .

The function is nothing suspicious:

```python
def merge_built_binaries(multi_pkg_list: MultiPackagesList, built_binaries: PackagesList):
    built_list = multi_pkg_list['Local Cache']

    # merge into built_binaries
    built_list_refs = built_list.refs()
    refs_is_dict = False
    # conan 2.0.10 and beyond
    if callable(getattr(built_list_refs, 'items', None)):
        built_list_refs = built_list_refs.items()
        refs_is_dict = True
    for ref, recipe_bundle in built_list_refs:
        built_binaries.add_refs([ref])
        built_list_prefs = built_list.prefs(ref, recipe_bundle)
        if refs_is_dict:
            built_list_prefs = built_list_prefs.items()
        for pref, _ in built_list_prefs:
            built_binaries.add_prefs(ref, [pref])
```

and even if I copy it into the same python file, the error is gone. So it must be some import from the file where the function resides.

And... it is.

```python
from conan.api.model import BINARY_MISSING
```

Some other functions in this file are using the `BINARY_MISSING` name. Did that change in v2.12?

**Comment by DoDoENT** [comment]
One function in our custom commands does this:

```python

    all_missing_binaries = []

    print_graph_packages(deps_graph)
    deps_graph.report_graph_error()

    if not build_dependencies:
        for node in deps_graph.ordered_iterate():
            if node.binary == BINARY_MISSING:
                all_missing_binaries.append(node.ref)
                if missing_ref is None:
                    missing_ref = node.ref
                    missing_conaninfo = node.conanfile.info

    if missing_ref and not build_dependencies:
        pkglist = conan_api.list.explain_missing_binaries(missing_ref, missing_conaninfo, remotes)
        raise MissingBinariesError(pkglist, all_missing_binaries)

```

It collects the list of packages with missing binaries so that a nice error with a list of all missing binaries can be printed, just like original `conan install` does.

**Comment by AbrilRBS** [comment]
Also note that your `cmd_merge_lists` is no longer necessary since Conan 2.3, where `conan pkglist merge` was introduced to acomplish the same :)

**Comment by DoDoENT** [comment]
> Also note that your `cmd_merge_lists` is no longer necessary since Conan 2.3, where `conan pkglist merge` was introduced to acomplish the same :)

Cool. My custom command predates this and is still used in some of our pipelines. We'll need to migrate those to use the official `conan pkglist merge`.

Thanks for letting me know!

**Comment by DoDoENT** [comment]
I did it this way:

```python
from conan import conan_version
from conan.tools.scm import Version

if conan_version < Version('2.12.0'):
    from conan.api.model import BINARY_MISSING
else:
    # This is a private API but I could not find an `BINARY_MISSING` import in the public API.
    from conans.client.graph.graph import BINARY_MISSING

```

Apparently `BINARY_MISSING` was part of public API before conan v2.12.0 and is now hidden within private API.

**Comment by memsharded** [comment]
> Apparently BINARY_MISSING was part of public API before conan v2.12.0 and is now hidden within private API.

Please recall the definition in https://docs.conan.io/2/introduction.html#stable

> Only documented features in https://docs.conan.io/ are considered part of the public interface of Conan. Private implementation details, and everything not included in the documentation is subject to change.


Being "importable" in Python code doesn't mean it is part of the public API. We are working trying to make it match, but due to ongoing development, experimental features, and other constraints, there is no match yet.

The BINARY_MISSING python string was never documented, it is an internal implementation detail Actually, this is one of the things that we will eventually move it to a proper enum type. So better not use ``from conan.api.model import BINARY_MISSING`` because it is not documented and it will most likely break in the future too.

What is a bit more documented, at least indirectly or partially, is the string in https://docs.conan.io/2/reference/commands/formatters/graph_info_json_formatter.html, see:

```json
"binary": "Missing"
```

So in general in user code it would be safer to do ``if binary == "Missing"``, than ``if binary == BINARY_MISSING``, as the value itself ``Missing`` is less likely to change because that is part of the public graph json output, and that will easily break more users.

**Comment by DoDoENT** [comment]
I understand, but both is flaky and in general I prefer using strongly typed values than rogue strings. Once it becomes an enum and part of the stable public API I'll update my code. In the meantime I'll keep up with conan updates and use unstable/private API where needed.

This is not the only place I need to use private/unstable API. I also need to use `Options` like this:

```python
from conan import conan_version

# This is a private API but I could not find an `Option` import in the public API.
if conan_version >= Version('2.12.0'):
    from conan.internal.model.options import Options
else:
    from conans.model.options import Options
```

I'm fully aware of the consequences.

Since this was the bug in my code after all, I'll close it as it has nothing to do with conan.

**Comment by memsharded** [comment]
> I understand, but both is flaky and in general I prefer using strongly typed values than rogue strings

That is true for regular programming. But when using a DSL like Conan recipes, things are not that direct. Consider for example:

```python
class Pkg(ConanFile):
     package_type = "shared-library"
```

The ``package_type`` is internally an Enum, with ``PackageType.SHARED`` values. But we don't document it because it will be more complex for the UX of the recipe in general. So what is documented and "stable" is the ``"shared-library"`` string. Conan will manage to automatically convert and validate those things, for example if someone does a ``if self.package_type != "sahred-lib"`` it will fail knowing the right side is an invalid value.

Something similar happens for ``binary`` field. The string values must be stable, because they are part of the external interface and the ``--format=json`` graph output. And when possible, Conan code will try to move to an Enum, meaning that ``if node.binary == "Missing"`` will also perform the same type of validation, making it even safer. 
But committing to a public interface of the Python classes or objects like ``BINARY_MISSING`` will effectively block development and disallow the introduction of such improvements that will make recipes and user code safer and more robust, because as part of the public API we will not be able to change it.

This is why we prefer to work with values in the user side (recipes, custom commands) than with classes and types.

In any case, as long as you are aware of the potential future breakages, all good, so thanks very much for your feedback!
