### ISSUE TITLE
[question] Access host architecture in package_info() of a toolchain package

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#13913]
### What is your question?

Hi,

pretend a toolchain package like this:

```
class Toolchain(ConanFile):
    name = "toolchain"
    version = "1.0.0-test"
    description = "toolchain package"
    settings = "arch"

    exports_sources = ("toolchain-*.cmake")

    def package(self):
        copy(self, pattern="toolchain-*.cmake", src=self.source_folder, dst=self.package_folder)

    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.build_type

    def package_info(self):
        toolchain_file = ""
        
        if self.settings.arch == "armv8": # TODO: this check is not working
            toolchain_file = os.path.join(self.package_folder, "toolchain-aarch64.cmake")
        elif self.settings.arch == "x86_64":
            toolchain_file = os.path.join(self.package_folder, "toolchain-x86_64.cmake")
            
        self.conf_info.append("tools.cmake.cmaketoolchain:user_toolchain", toolchain_file)
```

I want to bundle all CMake toolchain files in a single package. Dependent on the architecture of a consuming package which uses this package via `tool_requires` I want to pass the correct toolchain file.

How do I access the architecture of the consuming package? `self.settings.arch` seems to always represent the arch of the build context and is always `x86_64` in my setup. Or is there a mistake how I create the toolchain package `conan create toolchain.py --build-require -pr:h armv8 -pr:b default`? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

Thanks for your question.

For toolchain packages to be used as ``tool_requires``, the architecture of the "host" system is viewed from the recipe as ``self.settings_target.arch``:

- Build: The machine the toolchain is built from source/packaged: ``self.settings_build``
- Host: The machine the package will execute: ``self.settings``
- Target: For toolchains/cross-compilers used as ``tool_requires``, the machine that the package requiring it will run (the "host" of the consumer package): ``self.settings_target``

please let me know if this clarifies the issue

**Comment by Tobulus** [comment]
Hi @memsharded,

this fails with:
```
ERROR: toolchain/1.0.0-test: Error in package_info() method, line 24
        if self.settings_target.arch == "armv8":
        AttributeError: 'NoneType' object has no attribute 'arch'
```
for `conan create toolchain.py -s:h arch=armv8 -s:b arch=x86_64 --build-require` (not sure whether this is correct...)
Working example:
```
import os

from conan import ConanFile
from conan.tools.files import copy

class Toolchain(ConanFile):
    name = "toolchain"
    version = "1.0.0-test"
    description = "toolchain package"
    settings = "arch"

    exports_sources = ("toolchain-*.cmake")

    def package(self):
        copy(self, pattern="toolchain-*.cmake", src=self.source_folder, dst=self.package_folder)

    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.build_type

    def package_info(self):
        toolchain_file = ""
        
        if self.settings_target.arch == "armv8": # TODO: this check is not working
            toolchain_file = os.path.join(self.package_folder, "toolchain-aarch64.cmake")
        elif self.settings_target.arch == "x86_64":
            toolchain_file = os.path.join(self.package_folder, "toolchain-x86_64.cmake")
            
        self.conf_info.append("tools.cmake.cmaketoolchain:user_toolchain", toolchain_file)
```

**Comment by memsharded** [comment]
It works in Conan 2.0 without problems (well, you need to remove ``package_id()`` contents, because ``del self.info.settings.compiler`` is not possible in Conan 2.0 if the ``compiler`` is not a setting in the first place). 

It is very important to report the Conan version, otherwise we assume it is latest (Conan 2.0.5 at this moment).

For Conan 1.X you might need to check ``if self.settings_target is not None`` in some cases, but this specific case it seems to be working fine (Conan 1.60), I have just tested and it doesn't fail the way you report.

Could you please check it again?

**Comment by tbsuht** [comment]
I'm not sure what was the exact problem, but now it's working. Maybe I executed the wrong command on the CLI (e.g. `--build-require` missing). BTW: conan version was 1.57.0.

Thanks for the fast responses!
