### ISSUE TITLE
[bug]grpc/1.67.1 can't compile in windows 11 24H2 with VS2022 17.13

### ISSUE THREAD

**Issue by icegull** [conan-io/conan#17769]
### Describe the bug

OS: Windows 11 24H2 

conan version
version: 2.12.2
conan_path: C:\Program Files\Conan\conan\conan.exe
python
  version: 3.9.18
  sys_version: 3.9.18 (main, Oct  3 2023, 00:20:18) [MSC v.1929 64 bit (AMD64)]
  sys_executable: C:\Program Files\Conan\conan\conan.exe
  is_frozen: True
  architecture: AMD64
system
  version: 10.0.26100
  platform: Windows-10-10.0.26100-SP0
  system: Windows
  release: 10
  cpu: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel

conan profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.version=**194**
os=Windows

Description:
I add "self.requires("grpc/1.67.1")" and use "conan build . --output-folder=build --build=missing -s build_type=Release" to compile, I will have error:
**C:\Users\icegu\.conan2\p\b\grpc5a145ab5ccf80\b\src\third_party\upb\upb\message\internal\message.c(22,14): error C2099: initializer is not a constant [C:\Users\icegu\.conan2\p\b\grpc5a14
5ab5ccf80\b\build\upb_message_lib.vcxproj]**
grpc/1.67.1: ERROR: 
Package 'ac72e6c0c9291fc21bf3cf6b37b31fe25f3bd067' build failed
grpc/1.67.1: WARN: Build folder C:\Users\icegu\.conan2\p\b\grpc5a145ab5ccf80\b\build
ERROR: grpc/1.67.1: Error in build() method, line 254
        cmake.build()
        ConanException: Error 1 while executing

Could you check it and fix it? Also grpc has released 1.70.1, could you upgrade too? Thank you very much.

### How to reproduce it

Just add "self.requires("grpc/1.67.1")" and use "conan build . --output-folder=build --build=missing -s build_type=Release" to compile

**Comment by icegull** [comment]
FYI it's a known issue：
https://github.com/grpc/grpc/issues/37210

It's supposed to be fixed in 1.69. So if you can pump to the lastest 1.70.1, it will be perfect.

**Comment by memsharded** [comment]
I am doing a Windows build, first with the default profile (``compiler.cppstd=14``), to see if it reproduces too, because the package binary exists in ConanCenter, so maybe it is associated to ``compiler.cppstd=20`` only.

**Comment by memsharded** [comment]
It has built in my machine, but from your link:

> In the Windows 11 SDK 10.0.26100.0, the NAN macro is no longer a compile-time constant, causing issues with certain code constructs like constexpr. This can lead to compilation failures in code relying on NAN being a constant expression.

it seems a change in the SDK version, I was using a previous one.

So then it seems a bug in the library in combination with the latest SDK, not a Conan bug.

Conan has the ``-c tools.microsoft:winsdk_version`` conf to allow defining a specific sdk version if you also have installed the previous working one you could do that.

**Comment by icegull** [comment]
I am agree with you. This issue came from the WINDOWS SDK update. Anyway could you pump to a latest grpc? Or I have to ask grpc team to upload latest library?
Thank you for your help.

**Comment by memsharded** [comment]
Moving the ticket to conan-center-index, that would be the right place if the latest version of grpc is not there yet (please be patience, it might take a while until it lands)
