### ISSUE TITLE
Transitive shared library dependencies and rpath

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#18026]
Hello Conaneers!

I see a lot of posts here closely related to this issue, but not quite the same, so that's why I'm posting.

Conan 2.14.0
OS: WLS2 Ubuntu 20.04

I have a simple consumer recipe:
```
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake, cmake_layout
from conan import ConanFile
from conan.tools.files import copy, mkdir, save

class Consumer(ConanFile):
  name = "consumer"
  version = "0.0.0"
  settings = "os", "arch", "compiler", "build_type"
  package_type = "application"

  def requirements(self):
    self.requires("libcurl/8.4.0")

  def layout(self):
    cmake_layout(self)

  def export_sources(self):
    copy(self, "*", self.recipe_folder, self.export_sources_folder)

  def generate(self):
    tc = CMakeToolchain(self)
    tc.generate()

    deps = CMakeDeps(self)
    deps.generate()

  def build(self):
    cmake = CMake(self)
    cmake.configure(variables={
      "CMAKE_SKIP_RPATH": True
    })
    cmake.build()
```

I build the package with `conan create . -o:h *:shared=True -o:h libcurl/*:with_libssh2=True`

Getting this error finding the transitive libssh2.so file:
```
...
[100%] Linking CXX executable Test
/root/.cache/pypoetry/virtualenvs/sics-xS3fZVNL-py3.10/lib/python3.10/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/Test.dir/link.txt --verbose=1
/usr/bin/c++ -m64 -O3 -DNDEBUG -m64 -rdynamic CMakeFiles/Test.dir/main.o -o Test   -L/root/.conan2/p/b/libcu769ff685bed94/p/lib  -L/root/.conan2/p/opens0a355f078aac9/p/lib  -L/root/.conan2/p/zlib8781ef98e8c2c/p/lib  -L/root/.conan2/p/b/libss9baa4b159de10/p/lib  /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so -lrt -lpthread -ldl
/usr/bin/ld: warning: libssh2.so.1, needed by /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so: undefined reference to `libssh2_agent_disconnect'
/usr/bin/ld: /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so: undefined reference to `libssh2_session_hostkey'
/usr/bin/ld: /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so: undefined reference to `libssh2_sftp_readdir_ex'
/usr/bin/ld: /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so: undefined reference to `libssh2_session_init_ex'
...
```

The error essentially being `warning: libssh2.so.1 needed by /root/.conan2/p/b/libcu769ff685bed94/p/lib/libcurl.so, not found`

Please note the `CMAKE_SKIP_RPATH:True`. I want to use this for binary reproducibility reasons. If I set `CMAKE_SKIP_RPATH:False` it works due to rpath. 

I can also make it work if I express a direct dependency in libssh2 in my recipe. But I do not want to do that as I am not directly dependent on that package.

But how can I make it work without using rpath?

Could this be 'fixed' with the new CMakeConfigDeps class? I cannot try it due to the "AttributeError: 'NoneType' object has no attribute 'package_type'" error.

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Quick feedback:

```
 cmake.configure(variables={
      "CMAKE_SKIP_RPATH": True
    })
```
There is a CMakeToolchain ``rpath`` block, that you can define its ``skip_rpath=True`` value, so the value will go to the ``conan_toolchain.cmake`` file, so it is also used in ``conan install + cmake`` scenarios. This could also be valid with the ``CMakeToolchain.cache_variables`` definition.


Could you please share your ``CMakeLists.txt``. I'd say that it might do a ``target_link_libraries(myexecutable PRIVATE ...)``. If that is the case, try to change it to PUBLIC (it really doesn't matter, because this is an executble, so it won't ever be linked downstream).

> Could this be 'fixed' with the new CMakeConfigDeps class? I cannot try it due to the "AttributeError: 'NoneType' object has no attribute 'package_type'" error.

Yes, it would be worth to try the new ``CMakeConfigDeps`` generator, which I think it can solve this issue too, and that error might be solved if running from ``develop2`` source branch, as I think there was an issue with that package_type, that should be solved.

**Comment by klausholstjacobsen** [comment]
See my minimal test project here: https://github.com/klausholstjacobsen/conan-transitive-test

**Comment by klausholstjacobsen** [comment]
Substituting
```
    cmake.configure(variables={
      "CMAKE_SKIP_RPATH": True
    })
```
with
```
    tc = CMakeToolchain(self)  
    tc.blocks["rpath"].skip_rpath=True    
    tc.generate()
```

Produces identical results!

**Comment by klausholstjacobsen** [comment]
Confirmed to work with conan 2.15.0 and CMakeConfigDeps!
I am however wondering how mature CMakeConfigDeps is? Do you recommend to start using it, or is it only there for testing?

**Comment by AbrilRBS** [comment]
CMakeConfigDeps has now left the incubating stage and its usage is encouraged if possible. Closing this as solved, feel free to create new issues should you have any questions regarding CMakeConfigDeps, thanks! :)
