### ISSUE TITLE
[bug] error computing build order

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6484]
Since updating to conan 1.22 I receive an error when computing build order with
`conan graph build-order ./integration_deps --json=build_order.json --build=missing`

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 (64-bit)
  * Compiler+version: n/a
  * Conan version: 1.22
  * Python version: 3.7.4

### Steps to reproduce (Include if Applicable)
[1_21_2_conan.lock.txt](https://github.com/conan-io/conan/files/4171260/1_21_2_conan.lock.txt)
[1_22_0_conan.lock.txt](https://github.com/conan-io/conan/files/4171262/1_22_0_conan.lock.txt)

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
D:\JenkinsCI\workspace\Concepts\CI-PkgA\build>conan graph build-order ./integration_deps --json=build_order.json --build=missing
Using lockfile: 'D:\JenkinsCI\workspace\Concepts\CI-PkgA\build\integration_deps\conan.lock'
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\conans\client\command.py", line 1969, in run
    method(args[0][1:])
  File "c:\python37\lib\site-packages\conans\client\command.py", line 1801, in graph
    build_order = self._conan.build_order(args.lockfile, args.build)
  File "c:\python37\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "c:\python37\lib\site-packages\conans\client\conan_api.py", line 1216, in build_order
    reference = graph_info.graph_lock.root_node_ref()
  File "c:\python37\lib\site-packages\conans\model\graph_lock.py", line 185, in root_node_ref
    assert len(roots) == 1
AssertionError

ERROR:
```
    
>Can you check if that same command (with the same graph you have attached to the issue) was working in previous version?
```
Using lockfile: 'D:\JenkinsCI\workspace\Concepts\CI-PkgA\build\integration_deps\conan.lock'
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\conans\client\command.py", line 1947, in run
    method(args[0][1:])
  File "c:\python37\lib\site-packages\conans\client\command.py", line 1800, in graph
    build_order = self._conan.build_order(args.lockfile, args.build)
  File "c:\python37\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "c:\python37\lib\site-packages\conans\client\conan_api.py", line 1218, in build_order
    reference = graph_info.graph_lock.root_node_ref()
  File "c:\python37\lib\site-packages\conans\model\graph_lock.py", line 161, in root_node_ref
    total.extend(node.requires.values())
AttributeError: 'list' object has no attribute 'values'

ERROR: 'list' object has no attribute 'values'
```

**Comment by GordonJess** [comment]
Sorry, i meant version 1.22!

**Comment by GordonJess** [comment]
Perhaps `python_requires` need to be added to `total` [here](https://github.com/conan-io/conan/blob/773d73cb8d75cd0f5fda0621c0612a5f2f6637d9/conans/model/graph_lock.py#L184) so they are not counted as roots.

**Comment by jgsogo** [comment]
Hi, @GordonJess 

There have been changes in the `lockfiles` (and more to come) in order to allow some dynamism: when a package is modified it can also change the topology of the graph, when a package has to be built it may add some build_requires to the graph,... this is something we are struggling our heads with. Your use-case will help us with this, thanks!

I'll try to reduce your example to the bare minimum in order to reproduce the failure, so we can work on it.

**Comment by jgsogo** [comment]
I can see that your graph actually has several roots and this is problematic:
 * Can you check if that same command (with the same graph you have attached to the issue) was working in previous version?
 * Can you send to us the graph generated with the previous Conan version (if it is different)?

Thanks!

**Comment by GordonJess** [comment]
Hi @jgsogo ,

>Can you check if that same command (with the same graph you have attached to the issue) was working in previous version?
No, the same lockfile is not working with conan 1.21.2.  Please see the output above.

>Can you send to us the graph generated with the previous Conan version (if it is different)?
I've attached the lockfiles to this issue.

**Comment by GordonJess** [comment]
Hi again @jgsogo,

Would it be possible to include this issue in the upcoming 1.22.1 patch?  I appreciate that lockfiles are marked as experimental, but it is still a regression for the `conan graph` commands to break.

Even if I revert to 1.21.2 I am still blocked from implementing your suggested CI flow due to issue [6452](https://github.com/conan-io/conan/issues/6452).

Thanks a lot!

**Comment by jgsogo** [comment]
Hi! If this is a bug or regression we can add it to a patch version, don't worry about that. The main issue here is to know what is happening. I've drawn your two graphs and they look like correct, only one root:

### 1_21_2_conan.lock.txt

![image](https://user-images.githubusercontent.com/1406456/74171508-fa506200-4c2e-11ea-849a-cd79b34d5227.png)


### 1_22_0_conan.lock.txt

![image](https://user-images.githubusercontent.com/1406456/74171530-02a89d00-4c2f-11ea-9976-479aec18b40a.png)


...but in order to reproduce the issue I need all those packages to recreate the full graph. Can you simplify the graph and share with us the recipes needed to reproduce it?

---

PS.- The error you get using the graph with the previous version is because the format of the graphlock has changed, so older versions cannot read files generated with newer Conan.

**Comment by GordonJess** [comment]
I can get some package together for you tomorrow.  But from the graphs you can see that the 'baseline_for_lpcfioc_modules' package doesn't have any requires and so is probably mistaken as a root.  This is resolved as a python requires.

I had a look and couldn't find a graph lock test which included the new python_requires introduced in version 1.21.0.

**Comment by GordonJess** [comment]
Hi @jgsogo,

I had a bit more time to look into this today and I have a better idea of what is happening.  I was wrong before and it seems not related to the new `python_requires`, but rather the `build_requires`.

When first creating the lockfile I use the `--build` argument to ensure that `build_requires` dependencies are locked.

`conan graph lock my_app/0.1@user/testing --lockfile=release --build`
-> [init_conan.lock.txt](https://github.com/conan-io/conan/files/4185528/init_conan.lock.txt)

Then I create the new version of the package I was to integrate:

`cd my_pkg_a && conan create . my_pkg_a/0.2@user/testing --lockfile=../release`

All good so far.  Then I compute the build order of the missing packages:

`conan graph build-order ./release --json=bo.json --build=missing`
-> [updated_conan.lock.txt](https://github.com/conan-io/conan/files/4185598/updated_conan.lock.txt)

But here the `--build=missing` argument causes the `build_requires` of the newly built package `my_pkg_a` to be removed, since it is not missing.  However, the node of that `build_require` still remains in the graph, and since it is no longer required by any nodes it is deemed to be a root.
<br/>
Here is a package to recreate the error:
[conan_6484_bo.zip](https://github.com/conan-io/conan/files/4185659/conan_6484_bo.zip)

**Comment by jgsogo** [comment]
Thanks a lot! It totally makes sense. I'll reproduce it and add it to our test-suite.

**Comment by jgsogo** [comment]
I've added a test in the linked commit above, as you mention the `build_requires` relation is broken during the first call to `graph build-order ....` and it generates an invalid graphlock.

**Comment by memsharded** [comment]
This has been caused by the preparation of the code to be able to process "dynamic" lockfiles, that can be used to work with ``test_package`` for example.

I have submitted a possible fix (revert) in https://github.com/conan-io/conan/pull/6529, we should probably figure out a better solution when releasing the "dynamic" lockfiles

**Comment by memsharded** [comment]
#6529 merged, this will be released in 1.22.2
