### ISSUE TITLE
Conan 1.12.0 breaks existing recipes using Reference attributes

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4588]
Starting with conan 1.12.0 (currently using 1.12.2) our conan recipes no longer work, and fail with the following error during conan export:
```
ERROR: Traceback (most recent call last):
  File "d:\python37\lib\site-packages\conans\errors.py", line 24, in conanfile_exception_formatter
    yield
  File "d:\python37\lib\site-packages\conans\client\packager.py", line 73, in create_package
    conanfile.package()
  File "...\conanfile.py", line 43, in package
    super(NetCalcConan, self).package()
  File "d:\python37\lib\site-packages\conan_template\ConanTemplate.py", line 406, in package
    tools.save(os.path.join(self.package_folder, self.name + "Config.cmake"), self.generate_cmake_config())
  File "d:\python37\lib\site-packages\conan_template\ConanTemplate.py", line 416, in generate_cmake_config
    list(requirement_find_packages)
  File "d:\python37\lib\site-packages\conan_template\ConanTemplate.py", line 409, in <lambda>
    requirement_names = map(lambda it: it.conan_reference.name, filter(lambda it: not it.private, self.requires.values()))
AttributeError: 'Requirement' object has no attribute 'conan_reference'
```

This was probably caused by 3e2b35021d4d22b7ee642fef0e35469834b8ff37. Please revert this change resp. modify it such that the old property names are still available.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
Hi @sigiesec 

From Conan 1.0 there is a commitment for stability that includes only documented elements (https://docs.conan.io/en/latest/introduction.html?highlight=commitment#stable), we need to change the codebase implementation details to be able to evolve and include new functionalities, so this cannot be considered a regression neither a bug.

To access information about your dependencies consider using `deps_cpp_info`, `deps_env_info` or `deps_user_info` depending on your needs ([link to docs](https://docs.conan.io/en/latest/reference/conanfile/attributes.html)).

Thanks

**Comment by sigiesec** [comment]
Okay, thanks for the information, I wasn't aware that the Reference object is considered internal. Then I will try to change our recipe base to use the public data.

**Comment by sigiesec** [comment]
@jgsogo One question on this: Does self.deps_cpp_info.deps include private requirements?

**Comment by jgsogo** [comment]
Yes, it does.

**Comment by sigiesec** [comment]
Mh :( How can I filter out the private requirements then? Maybe this was the reason I was using self.requires.

**Comment by jgsogo** [comment]
That's a good question, and I'm running some trials and I think there is something to improve/document here because that list is different depending on the stage. I'm printing the list `self.deps_cpp_info.deps` in method `build` and `package_info`.
 * building a package, the list contains both private and public requirements (both, in method `build` and `package_info`).
 * consuming a package, the list contains only public requirements (method `package_info`, the `build` one is not executed)

So, **IMO here there is an inconsistency, I think that it is not ok to get a different list in the same method (`package_info`) depending on the context it is being called (build -vs- consume)**. 

I think it requires to spent a little time investigating this _bug_: check also `override` requirements (never appears) and `build_requirements` (like private ones).

**Comment by jgsogo** [comment]
About filtering, @sigiesec, when you are inside the recipe that is requiring other packages you have written all the information, so you can organize your code to use it:

```python
class ConanFile():
   ...
   public_req = "...."
   private_req = "..."
   requires = public_req + private_req

   def my_function(self):
      deps = self.deps_cpp_info.deps
      public = <filter using self.public_req>

```

**Comment by memsharded** [comment]
@jgsogo That is the definition of a conan private dependency. You only have it when you are building the package, not when you are consuming it.

I'd like to add that private dependencies should be used in very exceptional occasions, like if you are wrapping different versions of the same library because some legacy app needs to do that. Otherwise, I would avoid them as much as possible.

**Comment by sigiesec** [comment]
@jgsogo Thanks for the suggestion, but I fear this is nothing I can implement. On the one hand, the code that uses the reuqirements is in our base class for conanfiles and used in a large number of individual recipes. On the other hand, the whole reason I am not directly accessing some member I have under control is that the requirements might depend on the platform, e.g.

However, as @memsharded wrote, private requirements are rare. We used them before build_requires was introduced, and such uses remain at some points, but if I am lucky this is not relevant for the offending code, so I can ignore the privateness.

**Comment by jgsogo** [comment]
@memsharded, if I see a recipe like this, with a private-requirement, I would expect to have the same behavior when the `package_info` function is executed during the build and when it is executed during the consumption. 

```python
class Conanfile():
    def requirements(self):
        self.requries("AA/version@user/channel")
        self.requires("BB/version@user/channel", private=True)

    def package_info(self):
        if "BB" in self.deps_cpp_info.deps:
            self.output.info("Added important flags related to BB")
            self.cpp_info.defines = ["HAS_BB"]  # But 'HAS_BB' never reaches the consumers...
```

**Comment by memsharded** [comment]
That is a concept error. If BB is private for the consumers of this package, by definition you cannot affect affect consumers by anything related to this package. For consumers, BB should be like it doesn't exist, or do not make it private.

**Comment by jgsogo** [comment]
**Ok, that's the theory and we agree on it**, but the code is stubborn and if there is a possibility someone will be using it.  So in theory the list `self.deps_cpp_info.deps` should contain only _public_ requirements, never the private ones... at least in the `package_info` function, but what happens to the other methods?

Here there is something to fix, I'm not sure how neither if it is possible without breaking someone else recipes... maybe we need a `deps_cpp_info.deps` and `deps_cpp_info.deps_private` (like @sigiesec needs) and keep both lists with the same values regardless of the context (we can even raise if `deps_private` is accessed in `package_info`)... or maybe we can leave it as is for 1.x and propose for Conan 2.x to qualify each dep to know if it is public/private/buidl-requires,...
